/********************************************************************/
/* Applied Programming - Port of C++ program to C                   */
/* Linear Least Squares Curve Fitting.                              */
/* This program fits a line to the data points generated by         */
/* DataPoints () in the Data module (one data point per call).      */
/* Revised: Juan C. Cockburn, Sept 9, 2013 (uses realloc)  			*/
/* Edited: Vu X. Dinh, September 23, 2013					        */
/********************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "timer.h"

FILE *file;

typedef double Coordinate; /* for convenience and readability */

/*************************************************************************
 * "Header" structure of the dynamic array for storing coordinates points
 * prior for computing the "best" least squares line fit for a given set
 * of (X,Y) data points.
 *************************************************************************/
typedef struct {
	Coordinate *Data_X;    	/* Pointer to X data (i.e., a dynamic array). */
	Coordinate *Data_Y;   	/* Pointer to Y data (i.e., a dynamic array). */
	int Size;   				/* Size of dynamic arrays */
	int NextElement;   		/* Index of next data point to be stored. */
} DynamicArray;


/***********************************************************************
 * Function prototypes (implementations are after main)
 **********************************************************************/
void AddPoint (DynamicArray *DataSet, Coordinate X, Coordinate Y);
void CalculateCoefficients (DynamicArray *DataSet, Coordinate *A, Coordinate *B);

/********************************************************************/
/* Main program to fit a line to the data.                          */
/********************************************************************/
int main(int argc, char *argv[]) {

	DECLARE_TIMER(myTimer)
	START_TIMER(myTimer);

	/* Declare a DynamicArray data structure */
	DynamicArray myArray;

	/* Declare Variables to hold constant and linear coefficients of line */
	double A = 0.0;
	double B = 0.0;

	/* Declare Temporary variables to hold data read from file */
	double X = 0.0;
	double Y = 0.0;

	/* Check invocation from command line */
	if (argc <= 2) {
		/* Start with minimally sized arrays */

		/* Allocate the X and Y dynamic arrays with malloc */
		myArray.Data_X = malloc(10*sizeof(Coordinate));
		myArray.Data_Y = malloc(10*sizeof(Coordinate));

		/* Initialize the index where the next data point will go */
		myArray.Size = 10;
		myArray.NextElement = 0;

		/* While new a data point is available, add it to the list */

		file = fopen(argv[1], "r");

			if (file) {
				while (fscanf(file, "%lf %lf \n", &X, &Y) != EOF) {
				AddPoint(&myArray, X, Y);
				}
				fclose(file);
			}
			else {
				printf("Can't open the file.");
				exit(1);
			}

		/*
		while (DataPoints(&X,&Y))
		{
			AddPoint(&myArray, X, Y);
		}
		*/

		/* Calculate coefficients of Linear Fit */
		CalculateCoefficients(&myArray, &A, &B);

		/* Print equation of "best fit" line */

		printf("Y = %fX + %f\n", A, B);

		/* Return dynamic memory to the heap */
		free(myArray.Data_X);
		free(myArray.Data_Y);

	} /* if() */

	else {
		/* Display program usage information */
		/*** write your code here ***/
		printf("Error. Please check your command line.");

	}/* else () */

	/* STOP_TIMER(myTimer); */
	/* PRINT_TIMER(myTimer);*/

	return 0; /* successful execution */
} /* main() */

/***********************************************************************
 *  Local Functions Implementation
 **********************************************************************/

/***********************************************************************
 *  AddPoint() accepts a single point and adds it to the dynamic array.
 *  If necessary, the array size is expanded.
 **********************************************************************/
void AddPoint (DynamicArray *DataSet, Coordinate X, Coordinate Y) {
	/* Store the data point into the arrays */
	DataSet->Data_X[DataSet->NextElement] = X;
	DataSet->Data_Y[DataSet->NextElement] = Y;

	/* Increment the index for the next point; check array size. */
	if (++DataSet->NextElement >= DataSet->Size) {
		/* Double the size of the arrays */
		DataSet->Size = DataSet->Size << 1;

		/* Allocate new arrays with the new size */
		DataSet->Data_X =
				(Coordinate *) realloc(DataSet->Data_X,sizeof(Coordinate) * DataSet->Size);
		DataSet->Data_Y =
				(Coordinate *) realloc(DataSet->Data_Y,sizeof(Coordinate) * DataSet->Size);

	} /* if() */
} /* AddPoint () */


/********************************************************************/
/*  CalculateCoefficients() calculates A and B in Y = A * X + B     */
/********************************************************************/
void CalculateCoefficients (DynamicArray *DataSet, Coordinate *A, Coordinate *B) {
	/* Declare and initialize sum variables */
	double S_XX = 0.0;
	double S_XY = 0.0;
	double S_X  = 0.0;
	double S_Y  = 0.0;

	unsigned i;
	for (i = 0; i < DataSet->NextElement; i++)
	{
		S_XX += DataSet->Data_X[i] * DataSet->Data_X[i];
		S_XY += DataSet->Data_X[i] * DataSet->Data_Y[i];
		S_X  += DataSet->Data_X[i];
		S_Y  += DataSet->Data_Y[i];
	}

	/* Compute the constant */
	*B = (((S_XX * S_Y) - (S_XY * S_X)) / ((DataSet->NextElement * S_XX) - (S_X * S_X)));

	/* Compute the linear coefficient */
	*A = (((DataSet->NextElement * S_XY) - (S_X * S_Y)) / ((DataSet->NextElement * S_XX) - (S_X * S_X)));
}
